### ISSUE TITLE
How to use existing config files

### ISSUE THREAD

**Issue by daihuiao** [typoverflow/OfflineRL-Lib#16]
Not familiar with Utilsrl. I want to reproduce the results of some algorithms, but I don’t know where to start.(*￣︶￣)

**Comment by daihuiao** [comment]
And the experimental results on your Wandb seem to be unable to access because of authority issues, (*￣︶￣)
![image](https://github.com/typoverflow/OfflineRL-Lib/assets/74499474/4fd52cf6-c8de-4819-92a0-2e6227a140c4)

**Comment by typoverflow** [comment]
Sorry for the late replay. We have re-benchmarked the algorithms recently, and the wandb log link is not updated for now. I'm currently working on this and we will let you know as soon as the benchmarking is done.

**Comment by typoverflow** [comment]
> Not familiar with Utilsrl. I want to reproduce the results of some algorithms, but I don’t know where to start.(*￣︶￣)

Just use the command `python3 reproduce/{algo}/run_{algo}_d4rl.py --config reproduce/{algo}/config/d4rl/path/to/env_config.py`

**Comment by daihuiao** [comment]
Thank you very much for your reply. This is very helpful for me

**Comment by typoverflow** [comment]
Hey @daihuiao, the benchmark results are uploaded finally! If it is not too late, you can check them according to the guide in README.
