### ISSUE TITLE
Returns treated as returns-to-go

### ISSUE THREAD

**Issue by maskillj** [typoverflow/OfflineRL-Lib#21]
https://github.com/LAMDA-RL/OfflineRL-Lib/blame/988f9a1b7e55a9feee08c43824163ad37f6d7056/offlinerllib/policy/model_free/dt.py#L93

**Comment by typoverflow** [comment]
Hi, just saw this issue, sorry for the late replay. The returns here are actually return-to-gos, you can have a look at the calculation in D4RLTrajectoryReplay.

**Comment by maskillj** [comment]
> Hi, just saw this issue, sorry for the late replay. The returns here are actually return-to-gos, you can have a look at the calculation in D4RLTrajectoryReplay.

Seen thanks - apologies for the false alarm!
